"""Query (run-time, every user question).
Hybrid retrieve (dense Chroma + sparse BM25) -> RRF fuse -> grounded answer with
citations and an "I don't know" refusal. Optional metadata pre-filter.
Course parallel: notebook 3 (hybrid) + the metadata-filter notebook. The instructors'
line for support domains: start with hybrid. We do.
TODO (vibe session): add a cross-encoder reranker (the deck's "single biggest win",
v1.1); wire the metadata-filter LLM call into the UI.
"""
import os
import json
import pathlib
import chromadb
from rank_bm25 import BM25Okapi
from anthropic import Anthropic
from openai import OpenAI
from dotenv import load_dotenv
from embeddings import embed

load_dotenv()

CHROMA = pathlib.Path(__file__).parent.parent / "chroma_db"
MODEL = os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-6")
_anthropic = Anthropic()

# Nebius Token Factory — same prompt, open model, for model comparison (Week 2 requirement).
_nebius = OpenAI(
    base_url="https://api.tokenfactory.nebius.com/v1/",
    api_key=os.getenv("NEBIUS_API_KEY"),
)
NEBIUS_MODEL = os.getenv("NEBIUS_MODEL", "meta-llama/Llama-3.3-70B-Instruct")

SYSTEM = (
    "You are a customer-support assistant. Answer using ONLY the context below. "
    "Cite the chunk id in square brackets for every fact, like [T-1007]. "
    "If the answer is not in the context, say: \"I don't know based on the provided sources.\" "
    "Be concise and practical."
)
def _collection():
    client = chromadb.PersistentClient(path=str(CHROMA))
    return client.get_collection("support_kb")
def _rrf(rankings: list[list[str]], k: int = 60) -> dict[str, float]:
    # Reciprocal Rank Fusion (slide 27). k=60 is the common default.
    scores: dict[str, float] = {}
    for ranking in rankings:
        for rank, doc_id in enumerate(ranking):
            scores[doc_id] = scores.get(doc_id, 0.0) + 1.0 / (k + rank + 1)
    return scores
def retrieve(query: str, top_k: int = 5, where: dict | None = None):
    col = _collection()
    # Pull a wide net from each retriever, then fuse.
    n = 20
    # Dense
    dense = col.query(query_embeddings=embed([query]), n_results=n, where=where)
    dense_ids = dense["ids"][0]
    # Sparse (BM25) over the same corpus
    alldocs = col.get(where=where) if where else col.get()
    corpus_ids = alldocs["ids"]
    tokenised = [d.split() for d in alldocs["documents"]]
    bm25 = BM25Okapi(tokenised)
    scored = sorted(zip(corpus_ids, bm25.get_scores(query.split())), key=lambda x: -x[1])
    sparse_ids = [cid for cid, _ in scored[:n]]
    fused = _rrf([dense_ids, sparse_ids])
    top_ids = sorted(fused, key=lambda i: -fused[i])[:top_k]
    got = col.get(ids=top_ids)
    by_id = dict(zip(got["ids"], got["documents"]))
    return [(cid, by_id[cid]) for cid in top_ids if cid in by_id]
def answer(query: str, where: dict | None = None) -> str:
    chunks = retrieve(query, where=where)
    context = "\n\n".join(f"[{cid}] {text}" for cid, text in chunks)
    msg = _anthropic.messages.create(
        model=MODEL,
        max_tokens=600,
        system=SYSTEM,
        messages=[{"role": "user", "content": f"CONTEXT:\n{context}\n\nQUESTION: {query}"}],
    )
    return msg.content[0].text
def answer_nebius(query: str, where: dict | None = None) -> str:
    """Same retrieval + same prompt as answer(), generated by a Nebius-hosted
    open model (Llama 3.3 70B). For model comparison — Week 2 requirement."""
    chunks = retrieve(query, where=where)
    context = "\n\n".join(f"[{cid}] {text}" for cid, text in chunks)
    resp = _nebius.chat.completions.create(
        model=NEBIUS_MODEL,
        max_tokens=600,
        messages=[
            {"role": "system", "content": SYSTEM},
            {"role": "user", "content": f"CONTEXT:\n{context}\n\nQUESTION: {query}"},
        ],
    )
    return resp.choices[0].message.content

# Phrases that mean "the model couldn't ground an answer".
_REFUSAL_SIGNALS = ("i don't know", "based on the provided sources", "could not find")

ESCALATION_MESSAGES = {
    "warm": (
        "I want to make sure you get the right answer, so I'm passing this to one of our "
        "support specialists who can help you properly."
    ),
    "concise": "This one's best handled by a person. I'm connecting you with a support agent now.",
    "apologetic": (
        "I don't have a confident answer for this in our help articles, so I'm handing you "
        "to a human agent who can sort it out."
    ),
    "action": (
        "I'm not confident I can answer this accurately, so I'm escalating you to a support agent. "
        "They'll have the full picture and can take it from here."
    ),
}

_EMOTIONAL_SIGNALS = {"urgent", "frustrated", "angry", "disappointed", "still", "never", "please", "help me", "terrible", "awful"}
_TECHNICAL_SIGNALS = {"error", "broken", "bug", "crash", "failed", "api", "integration", "configure", "setup", "install"}

def _pick_escalation_message(query: str) -> str:
    lowered = query.lower()
    words = set(lowered.split())
    if words & _EMOTIONAL_SIGNALS or "help me" in lowered:
        return ESCALATION_MESSAGES["warm"]
    if len(query.split()) <= 6:
        return ESCALATION_MESSAGES["concise"]
    if words & _TECHNICAL_SIGNALS:
        return ESCALATION_MESSAGES["action"]
    return ESCALATION_MESSAGES["apologetic"]

def answer_with_escalation(query: str, where: dict | None = None) -> dict:
    """Answer the question, but if the system can't ground a confident answer,
    hand off to a human instead of just refusing. Returns a dict so the caller
    knows whether it answered or escalated, and why.
    """
    chunks = retrieve(query, where=where)
    reply = answer(query, where=where)

    refused = any(sig in reply.lower() for sig in _REFUSAL_SIGNALS)
    if refused or not chunks:
        closest = chunks[0][0] if chunks else None
        return {
            "status": "escalated",
            "message": _pick_escalation_message(query),
            "closest_source": closest,   # nearest article we found, for the agent
            "reason": "low confidence / no grounded answer",
        }
    return {
        "status": "answered",
        "message": reply,
        "sources": chunks,
    }

if __name__ == "__main__":
    print(answer("My tracking says delivered but I never got my hardware add-on."))